### ISSUE TITLE
Make it clearer how to enable Gutenberg for all post types

### ISSUE THREAD

**Issue by eshannon3** [Automattic/gutenberg-ramp#76]
When I enabled the plugin, I was boggled as to why only "Post" and "Page" showed up in the list of post types where I could turn Gutenberg on and off.

After some googling I found out I needed to explicitly set "show_in_rest" to be true in my CPTs. However, even after setting that, unregistering the CPTs, and reregistering the CPTs, Ramp still did not list any of my CPTs. It was only when I deactivated the Ramp plugin and reactivated it - then I was able to see all my CPTs and pick which ones to enable Gutenberg for.

I would like to see a message in the UI that makes it clearer - if any post types are not appearing here, either link off to documentation on how to make sure your CPT supports whatever's needed, or else just mention the specific "show_in_rest" setting and make it clear you'll also have to deactivate Ramp and reactivate it after the post type(s) have been re-registered.

It would also be really helpful if the Plugins page had a link to "Settings" which took you straight to Settings > Writing. It took me awhile to figure out where to find the list of post types to toggle.

**Comment by justnorris** [comment]
Hi @eshannon3!
Thanks for the bug report - the code has actually been added already to Ramp to avoid confusion: https://github.com/Automattic/gutenberg-ramp/pull/59 - it just hasn't been released on the .org plugin just yet - There will be a 1.1 update released real soon :)

Closing the issue because it's already fixed 👍
